/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2015-12-31 15:54:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ path + "/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta name=\"description\"\r\n");
      out.write("\tcontent=\"上海罗馥缇电子商务有限公司  内容管理系统\">\r\n");
      out.write("<meta name=\"author\" content=\"上海罗馥缇电子商务有限公司\">\r\n");
      out.write("<!-- The styles -->\r\n");
      out.write("<link id=\"bs-css\" href=\"");
      out.print(basePath);
      out.write("css/bootstrap-cerulean.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body {\r\n");
      out.write("\tpadding-bottom: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar-nav {\r\n");
      out.write("\tpadding: 9px 0;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<link href=\"");
      out.print(basePath);
      out.write("css/bootstrap-responsive.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.print(basePath);
      out.write("css/charisma-app.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.print(basePath);
      out.write("css/jquery-ui-1.8.21.custom.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link href='");
      out.print(basePath);
      out.write("css/fullcalendar.css' rel='stylesheet'>\r\n");
      out.write("<link href='");
      out.print(basePath);
      out.write("css/fullcalendar.print.css' rel='stylesheet'\r\n");
      out.write("\tmedia='print'>\r\n");
      out.write("<link href='");
      out.print(basePath);
      out.write("css/chosen.css' rel='stylesheet'>\r\n");
      out.write("<link href='");
      out.print(basePath);
      out.write("css/uniform.default.css' rel='stylesheet'>\r\n");
      out.write("<link href='");
      out.print(basePath);
      out.write("css/colorbox.css' rel='stylesheet'>\r\n");
      out.write("<link href='");
      out.print(basePath);
      out.write("css/jquery.cleditor.css' rel='stylesheet'>\r\n");
      out.write("<link href='");
      out.print(basePath);
      out.write("css/jquery.noty.css' rel='stylesheet'>\r\n");
      out.write("<link href='");
      out.print(basePath);
      out.write("css/noty_theme_default.css' rel='stylesheet'>\r\n");
      out.write("<link href='");
      out.print(basePath);
      out.write("css/elfinder.min.css' rel='stylesheet'>\r\n");
      out.write("<link href='");
      out.print(basePath);
      out.write("css/elfinder.theme.css' rel='stylesheet'>\r\n");
      out.write("<link href='");
      out.print(basePath);
      out.write("css/jquery.iphone.toggle.css' rel='stylesheet'>\r\n");
      out.write("<link href='");
      out.print(basePath);
      out.write("css/opa-icons.css' rel='stylesheet'>\r\n");
      out.write("<link href='");
      out.print(basePath);
      out.write("css/uploadify.css' rel='stylesheet'>\r\n");
      out.write("\r\n");
      out.write("<link href='");
      out.print(basePath);
      out.write("css/common.css' rel='stylesheet'>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var basePath =\"");
      out.print(basePath);
      out.write("\";\r\n");
      out.write("</script>\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.print(basePath);
      out.write("img/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- jQuery -->\r\n");
      out.write("\t<script src=\"");
      out.print(basePath);
      out.write("js/jquery-1.7.2.min.js\"></script>\r\n");
      out.write("\t<!-- jQuery UI -->\r\n");
      out.write("\t<script src=\"");
      out.print(basePath);
      out.write("js/jquery-ui-1.8.21.custom.min.js\"></script>\r\n");
      out.write("\t<!-- transition / effect library -->\r\n");
      out.write("\t<script src=\"");
      out.print(basePath);
      out.write("js/bootstrap-transition.js\"></script>\r\n");
      out.write("\t<!-- alert enhancer library -->\r\n");
      out.write("\t<script src=\"");
      out.print(basePath);
      out.write("js/bootstrap-alert.js\"></script>\r\n");
      out.write("\t<!-- modal / dialog library -->\r\n");
      out.write("\t<script src=\"");
      out.print(basePath);
      out.write("js/bootstrap-modal.js\"></script>\r\n");
      out.write("\t<!-- custom dropdown library -->\r\n");
      out.write("\t<script src=\"");
      out.print(basePath);
      out.write("js/bootstrap-dropdown.js\"></script>\r\n");
      out.write("\t<!-- scrolspy library -->\r\n");
      out.write("\t<script src=\"");
      out.print(basePath);
      out.write("js/bootstrap-scrollspy.js\"></script>\r\n");
      out.write("\t<!-- library for creating tabs -->\r\n");
      out.write("\t<script src=\"");
      out.print(basePath);
      out.write("js/bootstrap-tab.js\"></script>\r\n");
      out.write("\t<!-- library for advanced tooltip -->\r\n");
      out.write("\t<script src=\"");
      out.print(basePath);
      out.write("js/bootstrap-tooltip.js\"></script>\r\n");
      out.write("\t<!-- popover effect library -->\r\n");
      out.write("\t<script src=\"");
      out.print(basePath);
      out.write("js/bootstrap-popover.js\"></script>\r\n");
      out.write("\t<!-- button enhancer library -->\r\n");
      out.write("\t<script src=\"");
      out.print(basePath);
      out.write("js/bootstrap-button.js\"></script>\r\n");
      out.write("\t<!-- accordion library (optional, not used in demo) -->\r\n");
      out.write("\t<script src=\"");
      out.print(basePath);
      out.write("js/bootstrap-collapse.js\"></script>\r\n");
      out.write("\t<!-- carousel slideshow library (optional, not used in demo) -->\r\n");
      out.write("\t<script src=\"");
      out.print(basePath);
      out.write("js/bootstrap-carousel.js\"></script>\r\n");
      out.write("\t<!-- autocomplete library -->\r\n");
      out.write("\t<script src=\"");
      out.print(basePath);
      out.write("js/bootstrap-typeahead.js\"></script>\r\n");
      out.write("\t<!-- tour library -->\r\n");
      out.write("\t<script src=\"");
      out.print(basePath);
      out.write("js/bootstrap-tour.js\"></script>\r\n");
      out.write("\t<!-- library for cookie management -->\r\n");
      out.write("\t<script src=\"");
      out.print(basePath);
      out.write("js/jquery.cookie.js\"></script>\r\n");
      out.write("\t<!-- calander plugin -->\r\n");
      out.write("\t<script src='");
      out.print(basePath);
      out.write("js/fullcalendar.min.js'></script>\r\n");
      out.write("\t<!-- data table plugin -->\r\n");
      out.write("\t<script src='");
      out.print(basePath);
      out.write("js/jquery.dataTables.min.js'></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- chart libraries start -->\r\n");
      out.write("\t<script src=\"");
      out.print(basePath);
      out.write("js/excanvas.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(basePath);
      out.write("js/jquery.flot.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(basePath);
      out.write("js/jquery.flot.pie.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(basePath);
      out.write("js/jquery.flot.stack.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(basePath);
      out.write("js/jquery.flot.resize.min.js\"></script>\r\n");
      out.write("\t<!-- chart libraries end -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- select or dropdown enhancer -->\r\n");
      out.write("\t<script src=\"");
      out.print(basePath);
      out.write("js/jquery.chosen.min.js\"></script>\r\n");
      out.write("\t<!-- checkbox, radio, and file input styler -->\r\n");
      out.write("\t<script src=\"");
      out.print(basePath);
      out.write("js/jquery.uniform.min.js\"></script>\r\n");
      out.write("\t<!-- plugin for gallery image view -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t<!-- rich text editor library -->\r\n");
      out.write("\t<script src=\"");
      out.print(basePath);
      out.write("js/jquery.cleditor.min.js\"></script>\r\n");
      out.write("\t<!-- notification plugin -->\r\n");
      out.write("\t<script src=\"");
      out.print(basePath);
      out.write("js/jquery.noty.js\"></script>\r\n");
      out.write("\t<!-- file manager library -->\r\n");
      out.write("\t<script src=\"");
      out.print(basePath);
      out.write("js/jquery.elfinder.min.js\"></script>\r\n");
      out.write("\t<!-- star rating plugin -->\r\n");
      out.write("\t<script src=\"");
      out.print(basePath);
      out.write("js/jquery.raty.min.js\"></script>\r\n");
      out.write("\t<!-- for iOS style toggle switch -->\r\n");
      out.write("\t<script src=\"");
      out.print(basePath);
      out.write("js/jquery.iphone.toggle.js\"></script>\r\n");
      out.write("\t<!-- autogrowing textarea plugin -->\r\n");
      out.write("\t<script src=\"");
      out.print(basePath);
      out.write("js/jquery.autogrow-textarea.js\"></script>\r\n");
      out.write("\t<!-- multiple file upload plugin -->\r\n");
      out.write("\t<script src=\"");
      out.print(basePath);
      out.write("js/jquery.uploadify-3.1.min.js\"></script>\r\n");
      out.write("\t<!-- history.js for cross-browser state change on ajax -->\r\n");
      out.write("\t<script src=\"");
      out.print(basePath);
      out.write("js/jquery.history.js\"></script>\r\n");
      out.write("\t<!-- application script for Charisma demo -->\r\n");
      out.write("\t<script src=\"");
      out.print(basePath);
      out.write("js/charisma.js\"></script>\r\n");
      out.write("\t<!-- 表单验证 -->\r\n");
      out.write("\t<script src=\"");
      out.print(basePath);
      out.write("js/FormValid.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(basePath);
      out.write("js/FV_onBlur.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(basePath);
      out.write("laydate/laydate.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(basePath);
      out.write("js/SetTime.js\"></script>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
