/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2016-03-05 13:32:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.util.*;
import java.text.SimpleDateFormat;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/page/footer.jsp", Long.valueOf(1451708878700L));
    _jspx_dependants.put("/page/topbar.jsp", Long.valueOf(1451724714658L));
    _jspx_dependants.put("/page/leftmenu.jsp", Long.valueOf(1452169793553L));
    _jspx_dependants.put("/page/header.jsp", Long.valueOf(1457184681480L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\t<title>首页</title>\r\n");
      out.write("\t\t");
      out.write('\r');
      out.write('\n');

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ path + "/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta name=\"description\"\r\n");
      out.write("\tcontent=\"上海罗馥缇电子商务有限公司  内容管理系统\">\r\n");
      out.write("<meta name=\"author\" content=\"上海罗馥缇电子商务有限公司\">\r\n");
      out.write("<!-- The styles -->\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body {\r\n");
      out.write("\tpadding-bottom: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar-nav {\r\n");
      out.write("\tpadding: 9px 0;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\t<link href=\"");
      out.print(basePath);
      out.write("js/webuploader-0.1.5/webuploader.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link  href=\"css/bootstrap-cerulean.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print(basePath);
      out.write("css/charisma-app.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href='");
      out.print(basePath);
      out.write("css/fullcalendar.css' rel='stylesheet'>\r\n");
      out.write("    <link href='");
      out.print(basePath);
      out.write("css/fullcalendar.print.css' rel='stylesheet' media='print'>\r\n");
      out.write("    <link href='");
      out.print(basePath);
      out.write("css/chosen.min.css' rel='stylesheet'>\r\n");
      out.write("    <link href='");
      out.print(basePath);
      out.write("css/colorbox.css' rel='stylesheet'>\r\n");
      out.write("    <link href='");
      out.print(basePath);
      out.write("css/responsive-tables.css' rel='stylesheet'>\r\n");
      out.write("    <link href='");
      out.print(basePath);
      out.write("css/bootstrap-tour.min.css' rel='stylesheet'>\r\n");
      out.write("\t<link href='");
      out.print(basePath);
      out.write("css/jquery.noty.css' rel='stylesheet'>\r\n");
      out.write("\t<link href='");
      out.print(basePath);
      out.write("css/noty_theme_default.css' rel='stylesheet'>\r\n");
      out.write("    <link href='");
      out.print(basePath);
      out.write("css/elfinder.min.css' rel='stylesheet'>\r\n");
      out.write("    <link href='");
      out.print(basePath);
      out.write("css/elfinder.theme.css' rel='stylesheet'>\r\n");
      out.write("    <link href='");
      out.print(basePath);
      out.write("css/jquery.iphone.toggle.css' rel='stylesheet'>\r\n");
      out.write("    <link href='");
      out.print(basePath);
      out.write("css/uploadify.css' rel='stylesheet'>\r\n");
      out.write("    <link href='");
      out.print(basePath);
      out.write("css/animate.min.css' rel='stylesheet'>\r\n");
      out.write("    <link href='");
      out.print(basePath);
      out.write("css/style.css' rel='stylesheet'>\r\n");
      out.write("  <script src=\"");
      out.print(basePath);
      out.write("js/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var basePath =\"");
      out.print(basePath);
      out.write("\";\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<script src=\"");
      out.print(basePath);
      out.write("js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- library for cookie management -->\r\n");
      out.write("<script src=\"");
      out.print(basePath);
      out.write("js/jquery.cookie.js\"></script>\r\n");
      out.write("<!-- calender plugin -->\r\n");
      out.write("<script src='");
      out.print(basePath);
      out.write("js/moment.min.js'></script>\r\n");
      out.write("<script src='");
      out.print(basePath);
      out.write("js/fullcalendar.min.js'></script>\r\n");
      out.write("<!-- data table plugin -->\r\n");
      out.write("<script src='");
      out.print(basePath);
      out.write("js/jquery.dataTables.min.js'></script>\r\n");
      out.write("\r\n");
      out.write("<!-- select or dropdown enhancer -->\r\n");
      out.write("<script src=\"");
      out.print(basePath);
      out.write("js/chosen.jquery.min.js\"></script>\r\n");
      out.write("<!-- plugin for gallery image view -->\r\n");
      out.write("<script src=\"");
      out.print(basePath);
      out.write("js/jquery.colorbox-min.js\"></script>\r\n");
      out.write("<!-- notification plugin -->\r\n");
      out.write("<script src=\"");
      out.print(basePath);
      out.write("js/jquery.noty.js\"></script>\r\n");
      out.write("<!-- library for making tables responsive -->\r\n");
      out.write("<script src=\"");
      out.print(basePath);
      out.write("js/responsive-tables.js\"></script>\r\n");
      out.write("<!-- tour plugin -->\r\n");
      out.write("<script src=\"");
      out.print(basePath);
      out.write("js/bootstrap-tour.min.js\"></script>\r\n");
      out.write("<!-- star rating plugin -->\r\n");
      out.write("<script src=\"");
      out.print(basePath);
      out.write("js/jquery.raty.min.js\"></script>\r\n");
      out.write("<!-- for iOS style toggle switch -->\r\n");
      out.write("<script src=\"");
      out.print(basePath);
      out.write("js/jquery.iphone.toggle.js\"></script>\r\n");
      out.write("<!-- autogrowing textarea plugin -->\r\n");
      out.write("<script src=\"");
      out.print(basePath);
      out.write("js/jquery.autogrow-textarea.js\"></script>\r\n");
      out.write("<!-- multiple file upload plugin -->\r\n");
      out.write("<script src=\"");
      out.print(basePath);
      out.write("js/jquery.uploadify-3.1.min.js\"></script>\r\n");
      out.write("<!-- history.js for cross-browser state change on ajax -->\r\n");
      out.write("<script src=\"");
      out.print(basePath);
      out.write("js/jquery.history.js\"></script>\r\n");
      out.write("<!-- application script for Charisma demo -->\r\n");
      out.write("<script src=\"");
      out.print(basePath);
      out.write("js/charisma.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(basePath);
      out.write("js/common.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(basePath);
      out.write("js/webuploader-0.1.5/webuploader.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<style type=\"text/css\">\r\n");
      out.write("\t\t\tembed {\r\n");
      out.write("\t\t\t\twidth:100%;\r\n");
      out.write("\t\t\t\theight:520px\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<!-- topbar starts -->\r\n");
      out.write("\t\t");
      out.write('\r');
      out.write('\n');

	String path1 = request.getContextPath();
	String basePath1 = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ path1 + "/";

      out.write("\r\n");
      out.write("    <!-- topbar starts -->\r\n");
      out.write("    <div class=\"navbar navbar-default\" role=\"navigation\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"navbar-inner\">\r\n");
      out.write("            <button type=\"button\" class=\"navbar-toggle pull-left animated flip\">\r\n");
      out.write("                <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                <span class=\"icon-bar\"></span>\r\n");
      out.write("                <span class=\"icon-bar\"></span>\r\n");
      out.write("                <span class=\"icon-bar\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"index.html\"> <!-- <img alt=\"Charisma Logo\" src=\"img/logo20.png\" class=\"hidden-xs\"/> -->\r\n");
      out.write("                <span>Charisma</span></a>\r\n");
      out.write("\r\n");
      out.write("            <!-- user dropdown starts -->\r\n");
      out.write("            <div class=\"btn-group pull-right\">\r\n");
      out.write("                <button class=\"btn btn-default dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t\t<i class=\"glyphicon glyphicon-user\"></i><span class=\"hidden-sm hidden-xs\"> admin</span>\r\n");
      out.write("                    <span class=\"caret\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <ul class=\"dropdown-menu\">\r\n");
      out.write("                    <li><a href=\"login.html\">退出</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- user dropdown ends -->\r\n");
      out.write("\r\n");
      out.write("            <!-- theme selector starts -->\r\n");
      out.write("            <div class=\"btn-group pull-right theme-container animated tada\">\r\n");
      out.write("                <button class=\"btn btn-default dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("                    <i class=\"glyphicon glyphicon-tint\"></i><span\r\n");
      out.write("                        class=\"hidden-sm hidden-xs\">皮肤风格</span>\r\n");
      out.write("                    <span class=\"caret\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <ul class=\"dropdown-menu\" id=\"themes\">\r\n");
      out.write("                    <li><a data-value=\"classic\" href=\"#\"><i class=\"whitespace\"></i> Classic</a></li>\r\n");
      out.write("                    <li><a data-value=\"cerulean\" href=\"#\"><i class=\"whitespace\"></i> Cerulean</a></li>\r\n");
      out.write("                    <li><a data-value=\"cyborg\" href=\"#\"><i class=\"whitespace\"></i> Cyborg</a></li>\r\n");
      out.write("                    <li><a data-value=\"simplex\" href=\"#\"><i class=\"whitespace\"></i> Simplex</a></li>\r\n");
      out.write("                    <li><a data-value=\"darkly\" href=\"#\"><i class=\"whitespace\"></i> Darkly</a></li>\r\n");
      out.write("                    <li><a data-value=\"lumen\" href=\"#\"><i class=\"whitespace\"></i> Lumen</a></li>\r\n");
      out.write("                    <li><a data-value=\"slate\" href=\"#\"><i class=\"whitespace\"></i> Slate</a></li>\r\n");
      out.write("                    <li><a data-value=\"spacelab\" href=\"#\"><i class=\"whitespace\"></i> Spacelab</a></li>\r\n");
      out.write("                    <li><a data-value=\"united\" href=\"#\"><i class=\"whitespace\"></i> United</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- topbar ends -->");
      out.write("\r\n");
      out.write("\t\t<!-- topbar ends -->\r\n");
      out.write("\t\t<!-- \t<div class=\"container-fluid\"> -->\r\n");
      out.write("\t<div class=\"row-fluid\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- left menu starts -->\r\n");
      out.write("\t\t\t");
      out.write("\t\r\n");
      out.write("\r\n");

String path4LeftMenu = request.getContextPath();	

      out.write("\r\n");
      out.write("\t\t\t <div class=\"col-sm-2 col-lg-2\">\r\n");
      out.write("            <div class=\"sidebar-nav\">\r\n");
      out.write("                <div class=\"nav-canvas\">\r\n");
      out.write("                    <div class=\"nav-sm nav nav-stacked\">\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <ul class=\"nav nav-pills nav-stacked main-menu\">\r\n");
      out.write("                        <li class=\"nav-header\"><a\r\n");
      out.write("\t\t\t\t\thref=\"");
      out.print( path4LeftMenu );
      out.write("\">Main</a></li>\r\n");
      out.write("                        <li><a class=\"ajax-link\" href=\"queryPostList\"><i class=\"glyphicon glyphicon-home\"></i><span> 帖子列表</span></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                       <!--  <li><a class=\"ajax-link\" href=\"ui.html\"><i class=\"glyphicon glyphicon-eye-open\"></i><span> UI Features</span></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a class=\"ajax-link\" href=\"form.html\"><i\r\n");
      out.write("                                    class=\"glyphicon glyphicon-edit\"></i><span> Forms</span></a></li>\r\n");
      out.write("                        <li><a class=\"ajax-link\" href=\"chart.html\"><i class=\"glyphicon glyphicon-list-alt\"></i><span> Charts</span></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a class=\"ajax-link\" href=\"typography.html\"><i class=\"glyphicon glyphicon-font\"></i><span> Typography</span></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a class=\"ajax-link\" href=\"gallery.html\"><i class=\"glyphicon glyphicon-picture\"></i><span> Gallery</span></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-header hidden-md\">Sample Section</li>\r\n");
      out.write("                        <li><a class=\"ajax-link\" href=\"table.html\"><i\r\n");
      out.write("                                    class=\"glyphicon glyphicon-align-justify\"></i><span> Tables</span></a></li>\r\n");
      out.write("                        <li class=\"accordion\">\r\n");
      out.write("                            <a href=\"#\"><i class=\"glyphicon glyphicon-plus\"></i><span> Accordion Menu</span></a>\r\n");
      out.write("                            <ul class=\"nav nav-pills nav-stacked\">\r\n");
      out.write("                                <li><a href=\"#\">Child Menu 1</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Child Menu 2</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a class=\"ajax-link\" href=\"calendar.html\"><i class=\"glyphicon glyphicon-calendar\"></i><span> Calendar</span></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a class=\"ajax-link\" href=\"grid.html\"><i\r\n");
      out.write("                                    class=\"glyphicon glyphicon-th\"></i><span> Grid</span></a></li>\r\n");
      out.write("                        <li><a href=\"tour.html\"><i class=\"glyphicon glyphicon-globe\"></i><span> Tour</span></a></li>\r\n");
      out.write("                        <li><a class=\"ajax-link\" href=\"icon.html\"><i\r\n");
      out.write("                                    class=\"glyphicon glyphicon-star\"></i><span> Icons</span></a></li>\r\n");
      out.write("                        <li><a href=\"error.html\"><i class=\"glyphicon glyphicon-ban-circle\"></i><span> Error Page</span></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"login.html\"><i class=\"glyphicon glyphicon-lock\"></i><span> Login Page</span></a>\r\n");
      out.write("                        </li> -->\r\n");
      out.write("                        <li></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <label id=\"for-is-ajax\" for=\"is-ajax\"></label>\r\n");
      out.write("                    <br/><br/><br/><br/><br/><br/><br/><br/>\r\n");
      out.write("                    <br/><br/><br/><br/><br/><br/><br/><br/>\r\n");
      out.write("                    <br/><br/><br/><br/><br/><br/><br/><br/>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--/span-->\r\n");
      out.write("        <!-- left menu ends -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- left menu ends -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"content\" class=\"col-sm-10 col-lg-10\">\r\n");
      out.write("\t\t\t\t<!-- content starts -->\r\n");
      out.write("\t\t\t\t<ul class=\"breadcrumb\">\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t首页\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t系统概述\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<!-- content ends -->\r\n");
      out.write("\t\t\t\t<!-- \t\t\t</div>/#content.span10 -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--/fluid-row-->\r\n");
      out.write("\t\t\t<footer>\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</footer>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
